package com.zgh.onlinevideo.domain;

import java.util.Date;

/**
 * course_topic
 * 
 * @author zgh
 * @version 1.0.0 2020-11-16
 */
public class CourseTopic implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -2258144310408813662L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer id;

    /** title */
    private String title;

    /** coverUrl */
    private String coverUrl;

    /** intro */
    private String intro;

    /** introUrl */
    private String introUrl;

    /** views */
    private Integer views;

    /** flag */
    private Integer flag;

    /** courseTypeId */
    private Integer courseTypeId;

    /** createTime */
    private Date createTime;

    /** vipFlag */
    private Integer vipFlag;

    /** coursewareUrl */
    private String coursewareUrl;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取title
     * 
     * @return title
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * 设置title
     * 
     * @param title
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * 获取coverUrl
     * 
     * @return coverUrl
     */
    public String getCoverUrl() {
        return this.coverUrl;
    }

    /**
     * 设置coverUrl
     * 
     * @param coverUrl
     */
    public void setCoverUrl(String coverUrl) {
        this.coverUrl = coverUrl;
    }

    /**
     * 获取intro
     * 
     * @return intro
     */
    public String getIntro() {
        return this.intro;
    }

    /**
     * 设置intro
     * 
     * @param intro
     */
    public void setIntro(String intro) {
        this.intro = intro;
    }

    /**
     * 获取introUrl
     * 
     * @return introUrl
     */
    public String getIntroUrl() {
        return this.introUrl;
    }

    /**
     * 设置introUrl
     * 
     * @param introUrl
     */
    public void setIntroUrl(String introUrl) {
        this.introUrl = introUrl;
    }

    /**
     * 获取views
     * 
     * @return views
     */
    public Integer getViews() {
        return this.views;
    }

    /**
     * 设置views
     * 
     * @param views
     */
    public void setViews(Integer views) {
        this.views = views;
    }

    /**
     * 获取flag
     * 
     * @return flag
     */
    public Integer getFlag() {
        return this.flag;
    }

    /**
     * 设置flag
     * 
     * @param flag
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * 获取courseTypeId
     * 
     * @return courseTypeId
     */
    public Integer getCourseTypeId() {
        return this.courseTypeId;
    }

    /**
     * 设置courseTypeId
     * 
     * @param courseTypeId
     */
    public void setCourseTypeId(Integer courseTypeId) {
        this.courseTypeId = courseTypeId;
    }

    /**
     * 获取createTime
     * 
     * @return createTime
     */
    public Date getCreateTime() {
        return this.createTime;
    }

    /**
     * 设置createTime
     * 
     * @param createTime
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取vipFlag
     * 
     * @return vipFlag
     */
    public Integer getVipFlag() {
        return this.vipFlag;
    }

    /**
     * 设置vipFlag
     * 
     * @param vipFlag
     */
    public void setVipFlag(Integer vipFlag) {
        this.vipFlag = vipFlag;
    }

    /**
     * 获取coursewareUrl
     * 
     * @return coursewareUrl
     */
    public String getCoursewareUrl() {
        return this.coursewareUrl;
    }

    /**
     * 设置coursewareUrl
     * 
     * @param coursewareUrl
     */
    public void setCoursewareUrl(String coursewareUrl) {
        this.coursewareUrl = coursewareUrl;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}