package com.zgh.onlinevideo.domain;

/**
 * tool_item
 * 
 * @author zgh
 * @version 1.0.0 2020-11-16
 */
public class ToolItem implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 5746464460708853445L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer id;

    /** name */
    private String name;

    /** toolUrl */
    private String toolUrl;

    /** coverUrl */
    private String coverUrl;

    /** toolTypeId */
    private Integer toolTypeId;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取name
     * 
     * @return name
     */
    public String getName() {
        return this.name;
    }

    /**
     * 设置name
     * 
     * @param name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 获取toolUrl
     * 
     * @return toolUrl
     */
    public String getToolUrl() {
        return this.toolUrl;
    }

    /**
     * 设置toolUrl
     * 
     * @param toolUrl
     */
    public void setToolUrl(String toolUrl) {
        this.toolUrl = toolUrl;
    }

    /**
     * 获取coverUrl
     * 
     * @return coverUrl
     */
    public String getCoverUrl() {
        return this.coverUrl;
    }

    /**
     * 设置coverUrl
     * 
     * @param coverUrl
     */
    public void setCoverUrl(String coverUrl) {
        this.coverUrl = coverUrl;
    }

    /**
     * 获取toolTypeId
     * 
     * @return toolTypeId
     */
    public Integer getToolTypeId() {
        return this.toolTypeId;
    }

    /**
     * 设置toolTypeId
     * 
     * @param toolTypeId
     */
    public void setToolTypeId(Integer toolTypeId) {
        this.toolTypeId = toolTypeId;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}